spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api-cliente
    username: postgres
    password: 23548798
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true